# Generated by Django 5.1.1 on 2024-10-20 08:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название организации')),
                ('adress', models.CharField(max_length=200, verbose_name='Юридический адрес')),
                ('unp', models.CharField(max_length=200, verbose_name='УНП')),
                ('author', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredmetZakupki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_zakupki', models.CharField(max_length=200, verbose_name='Вид процедуры закупки')),
                ('nomer_dogovora', models.CharField(max_length=200, verbose_name='Номер договора')),
                ('data_dogovora', models.DateField(verbose_name='Дата заключения договора')),
                ('price_full', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость договора')),
                ('data_creator_zakupki', models.DateField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regforma.company')),
            ],
        ),
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_lot', models.PositiveIntegerField(default=1, verbose_name='Номер лота')),
                ('cod_okrb', models.CharField(max_length=200, verbose_name='Код ОКРБ')),
                ('predmet_zakupki', models.CharField(max_length=200, verbose_name='Предмет закупки (что закупаем)')),
                ('unit', models.IntegerField(verbose_name='Количество')),
                ('ed_izmer', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
                ('price_lot', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость лота (БезНДС), руб.')),
                ('zakupki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regforma.predmetzakupki')),
            ],
        ),
    ]
