# Generated by Django 5.1.4 on 2025-01-11 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zakupki', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lots',
            name='country',
            field=models.CharField(choices=[('RU', 'Россия'), ('BY', 'Беларусь'), ('US', 'США'), ('CN', 'Китай')], max_length=200, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='ed_izmer',
            field=models.CharField(choices=[('шт', 'штук'), ('м³', 'кубический метр (м³)'), ('л', 'литр (л)')], max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='zakupki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='regforma.predmetzakupki'),
        ),
        migrations.AlterField(
            model_name='predmetzakupki',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakupki', to='regforma.company'),
        ),
        migrations.AlterField(
            model_name='predmetzakupki',
            name='vid_zakupki',
            field=models.CharField(choices=[('Сравнительная таблица', 'Сравнительная таблица'), ('Прямая процедура', 'Прямая процедура'), ('Переход на прямую процедуру закупки', 'Переход на прямую процедуру закупки'), ('Упрощенная процедура закупки до 15 БВ', 'Упрощенная процедура закупки до 15 БВ'), ('Конкурентный лист', 'Конкурентный лист'), ('Открытый конкурс', 'Открытый конкурс')], max_length=200, verbose_name='Вид процедуры закупки'),
        ),
    ]
